 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: pretrain
  load_finetuned: True

  pretrained: "" #"https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained.pth"
  finetuned: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained.pth" #"/home/jupyter/t2v/LAVIS/lavis/output/BLIP2/spotlight_ret/20240118192/checkpoint_10.pth"

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp32"
  freeze_vit: True

  # Q-Former
  num_query_token: 32


preprocess:
    vis_processor:
      train:
        name: alpro_video_train
        n_frms: 4
        image_size: 224
        min_scale: 0.9
        max_scale: 1.0
        full_video: True
      eval:
        name: alpro_video_eval
        n_frms: 3
        image_size: 224
        min_scale: 0.9
        max_scale: 1.0
        full_video: True
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
